---
- name: Install Nginx
  hosts: all
  remote_user: ubuntu
  become: yes
  pre_tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
        force: yes
    - name: Install auditd
      command: apt-get --yes install auditd  
  vars:
    service_host: "www.praveenksarathi.com"
    service_admin_email: "kpraveen15703@gmail.com"
    service_name: "praveen"
    cwa_agent_mode: "ec2"
    cwa_aws_region: "eu-west-2"
    cwa_conf_json_file_content: "{{ lookup('file', 'files/nginx.json') | from_json }}"

  roles:
  - nginx
  - role: robertdebock.auditd
    auditd_local_events: "no"
    auditd_rules:
      - file: /var/log/audit/
        keyname: auditlog
      - file: /etc/audit/
        permissions:
          - write
          - attribute_change
        keyname: auditconfig
      - file: /var/log/nginx/
        keyname: nginx-audit  
  - service
  - role: christiangda.amazon_cloudwatch_agent # Config at file/nginx.json
